library(tidyverse)
library(nycflights13)

x1 <- c("Dec", "Apr", "Jan", "Mar")
x2 <- c("Dec", "Apr", "Jam", "Mar")
sort(x1)
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
y1 <- factor(x1, levels = month_levels)
y1
sort(y1)

y2 <- factor(x2, levels = month_levels)
# values not in levels get NA value
y2
# To get an error
y2 <- parse_factor(x2, levels = month_levels)

# Levels generated by default are in ascending alphabetical order
factor(x1)
# To get the level same as the values use unique or 
f1 <- factor(x1, levels = unique(x1))
f1
f1 <- factor(x1, fct_inorder(x1))
f1
f2 <- x1 %>% factor() %>% fct_inorder()
f2
levels(f2)

gss_cat
gss_cat %>%
  count(race)

ggplot(gss_cat,aes(race)) +
  geom_bar()

# By default, ggplot2 will drop levels that don’t have any values
# scale_x_discrete() is used to show the levels that have no value in the tibble
ggplot(gss_cat,aes(race)) +
  geom_bar() + scale_x_discrete(drop=FALSE)

religon=gss_cat %>%
  group_by(relig) %>% summarize(age=mean(age,na.rm=T),tvhours=mean(tvhours,na.rm=T),n=n())
religon
ggplot(religon)+
  geom_point(aes(tvhours,relig))

religon$relig
levels(religon$relig)
# fct_reorder to reorder the relig on the basis of tvhours  
# The values don't change but the levels are get sorted in ascending order based on the condition
fct_reorder(religon$relig, religon$tvhours)
ggplot(religon, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()
religon %>%
  mutate(relig = fct_reorder(relig, tvhours)) %>%
  ggplot(aes(tvhours, relig)) +
  geom_point()

religon %>%
  mutate(relig = fct_reorder(relig, tvhours))

rincome <- gss_cat %>%
  group_by(rincome) %>%
  summarize(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )
rincome

ggplot( rincome,aes(age, fct_reorder(rincome, age)))
        + geom_point()





